# build stage
FROM maven:3-jdk-8 as builder

ARG ERROR_INCLUDE_TRACE
ARG STORAGE_REPO_HOST
ARG STORAGE_REPO_ACCESS_KEY
ARG STORAGE_REPO_SECRET_KEY

ENV ERROR_INCLUDE_TRACE ${ERROR_INCLUDE_TRACE}
ENV STORAGE_REPO_HOST ${STORAGE_REPO_HOST}
ENV STORAGE_REPO_ACCESS_KEY ${STORAGE_REPO_ACCESS_KEY}
ENV STORAGE_REPO_SECRET_KEY ${STORAGE_REPO_SECRET_KEY}

RUN mkdir -p /usr/src/app
COPY . /usr/src/app
WORKDIR /usr/src/app
RUN mvn clean package

# run stage
FROM openjdk:8-jre-alpine

ARG STORAGE_PORT
ARG STORAGE_REPO_HOST
ARG STORAGE_REPO_ACCESS_KEY
ARG STORAGE_REPO_SECRET_KEY
ARG STORAGE_FLUENTD_HOST
ARG STORAGE_FLUENTD_PORT
ARG STORAGE_PROXY_HOSTNAME
ARG OAUTH2_ACCESS_TOKEN_URI
ARG OAUTH2_PROTECTED_URIS
ARG OAUTH2_CLIENT_ID
ARG OAUTH2_CLIENT_SECRET
ARG SSL_VERIFYING_DISABLE
ARG ERROR_INCLUDE_TRACE

ENV STORAGE_PORT ${STORAGE_PORT}
ENV STORAGE_REPO_HOST ${STORAGE_REPO_HOST}
ENV STORAGE_REPO_ACCESS_KEY ${STORAGE_REPO_ACCESS_KEY}
ENV STORAGE_REPO_SECRET_KEY ${STORAGE_REPO_SECRET_KEY}
ENV STORAGE_FLUENTD_HOST ${STORAGE_FLUENTD_HOST}
ENV STORAGE_FLUENTD_PORT ${STORAGE_FLUENTD_PORT}
ENV STORAGE_PROXY_HOSTNAME ${STORAGE_PROXY_HOSTNAME}
ENV OAUTH2_ACCESS_TOKEN_URI ${OAUTH2_ACCESS_TOKEN_URI}
ENV OAUTH2_PROTECTED_URIS ${OAUTH2_PROTECTED_URIS}
ENV OAUTH2_CLIENT_ID ${OAUTH2_CLIENT_ID}
ENV OAUTH2_CLIENT_SECRET ${OAUTH2_CLIENT_SECRET}
ENV SSL_VERIFYING_DISABLE ${SSL_VERIFYING_DISABLE}
ENV ERROR_INCLUDE_TRACE ${ERROR_INCLUDE_TRACE}

COPY --from=builder /usr/src/app/target/fdns-ms-storage-*.jar /app.jar

# pull latest
RUN apk update && apk upgrade --no-cache

# don't run as root user
RUN chown 1001:0 /app.jar
RUN chmod g+rwx /app.jar
USER 1001

ENTRYPOINT java -Dserver.tomcat.protocol-header=x-forwarded-proto -Dserver.tomcat.remote-ip-header=x-forwarded-for -jar /app.jar