version: '3'
services:
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server ~/Downloads/minio
  fluentd:
    image: fluent/fluentd
    ports:
      - "24224:24224"